
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


 
export enum GiftFilterType {
    /**
     * 无，全部获得
     */
    None = 0,
    /**
     * 随机获得N件
     */
    Random = 1,
    /**
     * 自定义选择N件
     */
    Custom = 2,
}

 
 
export enum GiftModelType {
    /**
     * 不可预览
     */
    Non = 0,
    /**
     * 单一预览
     */
    Single = 1,
    /**
     * 整套预览
     */
    Complete = 2,
    /**
     * 分开预览
     */
    Enumeration = 3,
    /**
     * 组合预览
     */
    Combination = 4,
}

 
 
export enum GiftUIType {
    /**
     * 普通界面
     */
    Normal = 0,
    /**
     * 特殊界面
     */
    Style_1 = 1,
}

 
 
export enum ItemCanUse {
    /**
     * 不能使用
     */
    CanNot = 0,
    /**
     * 只能单个使用
     */
    UseOne = 1,
    /**
     * 可以一键使用全部
     */
    UseTotal = 2,
}

 
 
export enum ItemEPrompt {
    /**
     * 否
     */
    NONE = 0,
    /**
     * 新装备
     */
    NEW_EQUIP = 1,
    /**
     * 红点
     */
    RED_POINT = 2,
}

 
 
export enum ItemLevelColor {
    /**
     * 蓝色
     */
    B = 0,
    /**
     * 紫色
     */
    A = 1,
    /**
     * 橙色
     */
    S = 2,
    /**
     * 红色
     */
    SR = 3,
    /**
     * 金色
     */
    SSR = 4,
}

 
 
export enum ItemSubType {
    /**
     * 无
     */
    NONE = 0,
    /**
     * 武器
     */
    WEAPON = 1,
    /**
     * 胸
     */
    CHEST = 2,
    /**
     * 腰带
     */
    BELT = 3,
    /**
     * 鞋子
     */
    BOOT = 4,
    /**
     * 戒指
     */
    RING = 5,
}

 
 
export enum ItemType {
    /**
     * 道具
     */
    Item = 0,
    /**
     * 消耗品
     */
    Expendable = 1,
    /**
     * 装备
     */
    Equip = 2,
    /**
     * 碎片
     */
    Fragment = 3,
    /**
     * 材料
     */
    Material = 4,
    /**
     * 任务
     */
    Task = 5,
}

 
 
export enum ItemUseLimiteType {
    /**
     * 无限制
     */
    NOLIMITE = 0,
    /**
     * 日限制
     */
    DAYLIMITE = 1,
    /**
     * vip限制
     */
    VIPLIMITE = 2,
    /**
     * 周限制
     */
    WEEK6LIMITE = 3,
}

 




export namespace Local {
export class Localization {

    constructor(_json_: any) {
        if (_json_.key === undefined) { throw new Error() }
        this.key = _json_.key
        if (_json_.ChineseSimplified === undefined) { throw new Error() }
        this.ChineseSimplified = _json_.ChineseSimplified
        if (_json_.ChineseTraditional === undefined) { throw new Error() }
        this.ChineseTraditional = _json_.ChineseTraditional
        if (_json_.English === undefined) { throw new Error() }
        this.English = _json_.English
        if (_json_.Japanese === undefined) { throw new Error() }
        this.Japanese = _json_.Japanese
        if (_json_.Korean === undefined) { throw new Error() }
        this.Korean = _json_.Korean
        if (_json_.Thai === undefined) { throw new Error() }
        this.Thai = _json_.Thai
        if (_json_.Indonesian === undefined) { throw new Error() }
        this.Indonesian = _json_.Indonesian
        if (_json_.French === undefined) { throw new Error() }
        this.French = _json_.French
        if (_json_.German === undefined) { throw new Error() }
        this.German = _json_.German
        if (_json_.Russian === undefined) { throw new Error() }
        this.Russian = _json_.Russian
        if (_json_.Italian === undefined) { throw new Error() }
        this.Italian = _json_.Italian
        if (_json_.PortuguesePortugal === undefined) { throw new Error() }
        this.PortuguesePortugal = _json_.PortuguesePortugal
        if (_json_.Spanish === undefined) { throw new Error() }
        this.Spanish = _json_.Spanish
        if (_json_.Vietnamese === undefined) { throw new Error() }
        this.Vietnamese = _json_.Vietnamese
    }

    /**
     * ID
     */
    readonly key: string
    /**
     * 简体中心
     */
    readonly ChineseSimplified: string
    /**
     * 繁体中心
     */
    readonly ChineseTraditional: string
    /**
     * 英语
     */
    readonly English: string
    /**
     * 日语
     */
    readonly Japanese: string
    /**
     * 韩语
     */
    readonly Korean: string
    /**
     * 泰语
     */
    readonly Thai: string
    /**
     * 印尼语
     */
    readonly Indonesian: string
    /**
     * 法语
     */
    readonly French: string
    /**
     * 德语
     */
    readonly German: string
    /**
     * 俄语
     */
    readonly Russian: string
    /**
     * 意大利语
     */
    readonly Italian: string
    /**
     * 葡萄牙语
     */
    readonly PortuguesePortugal: string
    /**
     * 西班牙语
     */
    readonly Spanish: string
    /**
     * 越南语
     */
    readonly Vietnamese: string

    resolve(tables:TablesComponent) {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}

}



/**
 * 属性
 */
export class Property {

    constructor(_json_: any) {
        if (_json_.PhysicalAttack === undefined) { throw new Error() }
        this.PhysicalAttack = _json_.PhysicalAttack
        if (_json_.MagicAttack === undefined) { throw new Error() }
        this.MagicAttack = _json_.MagicAttack
        if (_json_.PhysicalDefense === undefined) { throw new Error() }
        this.PhysicalDefense = _json_.PhysicalDefense
        if (_json_.MagicDefense === undefined) { throw new Error() }
        this.MagicDefense = _json_.MagicDefense
        if (_json_.Life === undefined) { throw new Error() }
        this.Life = _json_.Life
        if (_json_.Crit === undefined) { throw new Error() }
        this.Crit = _json_.Crit
        if (_json_.burstDamage === undefined) { throw new Error() }
        this.burstDamage = _json_.burstDamage
        if (_json_.precise === undefined) { throw new Error() }
        this.precise = _json_.precise
        if (_json_.block === undefined) { throw new Error() }
        this.block = _json_.block
    }

    /**
     * 物理攻击
     */
    readonly PhysicalAttack: number
    /**
     * 魔法攻击
     */
    readonly MagicAttack: number
    /**
     * 物理防御
     */
    readonly PhysicalDefense: number
    /**
     * 魔法防御
     */
    readonly MagicDefense: number
    /**
     * 生命值
     */
    readonly Life: number
    /**
     * 暴击
     */
    readonly Crit: number
    /**
     * 爆伤
     */
    readonly burstDamage: number
    /**
     * 精准
     */
    readonly precise: number
    /**
     * 格挡
     */
    readonly block: number

    resolve(tables:TablesComponent) {
        
        
        
        
        
        
        
        
        
    }
}





export class PropItem {

    constructor(_json_: any) {
        if (_json_.Id === undefined) { throw new Error() }
        this.Id = _json_.Id
        if (_json_.Count === undefined) { throw new Error() }
        this.Count = _json_.Count
    }

    /**
     * 道具id
     */
    readonly Id: number
    /**
     * 道具数量
     */
    readonly Count: number

    resolve(tables:TablesComponent) {
        
        
    }
}




export namespace Tables {
export class AchievementConfig {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.image === undefined) { throw new Error() }
        this.image = _json_.image
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.achievement_content === undefined) { throw new Error() }
        this.achievementContent = _json_.achievement_content
        if (_json_.LockText === undefined) { throw new Error() }
        this.LockText = _json_.LockText
        if (_json_.achievement_unlock_condition === undefined) { throw new Error() }
        { this.achievementUnlockCondition = []; for(let _ele0 of _json_.achievement_unlock_condition) { let _e0; _e0 = _ele0; this.achievementUnlockCondition.push(_e0);}}
    }

    /**
     * ID
     */
    readonly id: number
    /**
     * 成就对应的图标id
     */
    readonly image: number
    /**
     * 成就Key
     */
    readonly name: string
    /**
     * 成就内容Key
     */
    readonly achievementContent: string
    /**
     * 未解锁文字key
     */
    readonly LockText: string
    /**
     * 成就解锁条件
     */
    readonly achievementUnlockCondition: number[]

    resolve(tables:TablesComponent) {
        
        
        
        
        
        
    }
}

}


export namespace Tables {
export class ItemConfig {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.Name === undefined) { throw new Error() }
        this.Name = _json_.Name
        if (_json_.Type === undefined) { throw new Error() }
        this.Type = _json_.Type
        if (_json_.SubType === undefined) { throw new Error() }
        this.SubType = _json_.SubType
        if (_json_.EPrompt === undefined) { throw new Error() }
        this.EPrompt = _json_.EPrompt
        if (_json_.CanUse === undefined) { throw new Error() }
        this.CanUse = _json_.CanUse
        if (_json_.IsDecompose === undefined) { throw new Error() }
        this.IsDecompose = _json_.IsDecompose
        if (_json_.MaxNum === undefined) { throw new Error() }
        this.MaxNum = _json_.MaxNum
        if (_json_.description === undefined) { throw new Error() }
        this.description = _json_.description
        if (_json_.ComeLink === undefined) { throw new Error() }
        { this.ComeLink = []; for(let _ele0 of _json_.ComeLink) { let _e0; _e0 = _ele0; this.ComeLink.push(_e0);}}
        if (_json_.Icon === undefined) { throw new Error() }
        this.Icon = _json_.Icon
        if (_json_.BgIcon === undefined) { throw new Error() }
        this.BgIcon = _json_.BgIcon
        if (_json_.LevelColor === undefined) { throw new Error() }
        this.LevelColor = _json_.LevelColor
        if (_json_.CanAnnounce === undefined) { throw new Error() }
        this.CanAnnounce = _json_.CanAnnounce
        if (_json_.LinkInfo === undefined) { throw new Error() }
        this.LinkInfo = _json_.LinkInfo
        if (_json_.FunctionID === undefined) { throw new Error() }
        this.FunctionID = _json_.FunctionID
        if (_json_.UseLimiteType === undefined) { throw new Error() }
        this.UseLimiteType = _json_.UseLimiteType
        if (_json_.Abandon === undefined) { throw new Error() }
        this.Abandon = _json_.Abandon
        if (_json_.doubleCheckDesc === undefined) { throw new Error() }
        this.doubleCheckDesc = _json_.doubleCheckDesc
        if (_json_.CanTrade === undefined) { throw new Error() }
        this.CanTrade = _json_.CanTrade
        if (_json_.TradeCD === undefined) { throw new Error() }
        this.TradeCD = _json_.TradeCD
        if (_json_.TradeItemsLimit === undefined) { throw new Error() }
        this.TradeItemsLimit = _json_.TradeItemsLimit
        if (_json_.UseLinmit === undefined) { throw new Error() }
        this.UseLinmit = _json_.UseLinmit
        if(_json_.ExpireTime != undefined) { this.ExpireTime = _json_.ExpireTime } else { this.ExpireTime = undefined }
        if (_json_.IsRecordLog === undefined) { throw new Error() }
        this.IsRecordLog = _json_.IsRecordLog
    }

    /**
     * ID
     */
    readonly id: number
    readonly Name: string
    /**
     * 道具类型
     */
    readonly Type: ItemType
    /**
     * 子类别
     */
    readonly SubType: ItemSubType
    /**
     * 是否提示使用
     */
    readonly EPrompt: ItemEPrompt
    /**
     * 能否使用
     */
    readonly CanUse: ItemCanUse
    /**
     * 是否可分解
     */
    readonly IsDecompose: boolean
    /**
     * 叠加数
     */
    readonly MaxNum: number
    /**
     * 描述信息
     */
    readonly description: string
    /**
     * 来源链接
     */
    readonly ComeLink: number[]
    /**
     * 图标链接
     */
    readonly Icon: string
    /**
     * 背景图链接
     */
    readonly BgIcon: string
    /**
     * 颜色品级
     */
    readonly LevelColor: ItemLevelColor
    /**
     * 是否公告
     */
    readonly CanAnnounce: boolean
    /**
     * 点击使用后<br/>跳转位置
     */
    readonly LinkInfo: string
    /**
     * 关联的功能序号
     */
    readonly FunctionID: number
    /**
     * 使用限制类别
     */
    readonly UseLimiteType: ItemUseLimiteType
    /**
     * 是否废弃
     */
    readonly Abandon: boolean
    /**
     * 使用时需要弹窗二次确认的描述
     */
    readonly doubleCheckDesc: boolean
    /**
     * 能否交换
     */
    readonly CanTrade: boolean
    /**
     * 交换冷却CD<br/>
     */
    readonly TradeCD: number
    /**
     * 赠送数量限制
     */
    readonly TradeItemsLimit: number
    /**
     * 可使用总次数
     */
    readonly UseLinmit: number
    /**
     * 到期时间
     */
    readonly ExpireTime: number|undefined
    /**
     * 是否记录日志
     */
    readonly IsRecordLog: boolean

    resolve(tables:TablesComponent) {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}

}


export namespace Tables {
export class SoundsConfig {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.groupName === undefined) { throw new Error() }
        this.groupName = _json_.groupName
        if (_json_.path === undefined) { throw new Error() }
        this.path = _json_.path
        if (_json_.title === undefined) { throw new Error() }
        this.title = _json_.title
        if (_json_.characterName === undefined) { throw new Error() }
        this.characterName = _json_.characterName
    }

    /**
     * ID
     */
    readonly id: number
    /**
     * 声音所属组
     */
    readonly groupName: string
    /**
     * 声音所在的路径
     */
    readonly path: string
    /**
     * 声音标题Key
     */
    readonly title: string
    readonly characterName: string

    resolve(tables:TablesComponent) {
        
        
        
        
        
    }
}

}



export class vec2 {

    constructor(_json_: any) {
        if (_json_.x === undefined) { throw new Error() }
        this.x = _json_.x
        if (_json_.y === undefined) { throw new Error() }
        this.y = _json_.y
    }

    readonly x: number
    readonly y: number

    resolve(tables:TablesComponent) {
        
        
    }
}





export class vec3 {

    constructor(_json_: any) {
        if (_json_.x === undefined) { throw new Error() }
        this.x = _json_.x
        if (_json_.y === undefined) { throw new Error() }
        this.y = _json_.y
        if (_json_.z === undefined) { throw new Error() }
        this.z = _json_.z
    }

    readonly x: number
    readonly y: number
    readonly z: number

    resolve(tables:TablesComponent) {
        
        
        
    }
}





export class vec4 {

    constructor(_json_: any) {
        if (_json_.x === undefined) { throw new Error() }
        this.x = _json_.x
        if (_json_.y === undefined) { throw new Error() }
        this.y = _json_.y
        if (_json_.z === undefined) { throw new Error() }
        this.z = _json_.z
        if (_json_.w === undefined) { throw new Error() }
        this.w = _json_.w
    }

    readonly x: number
    readonly y: number
    readonly z: number
    readonly w: number

    resolve(tables:TablesComponent) {
        
        
        
        
    }
}





export namespace Tables {
export class TbAchievementConfig {
    private _dataMap: Map<number, Tables.AchievementConfig>
    private _dataList: Tables.AchievementConfig[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, Tables.AchievementConfig>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: Tables.AchievementConfig
            _v = new Tables.AchievementConfig(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, Tables.AchievementConfig> { return this._dataMap; }
    getDataList(): Tables.AchievementConfig[] { return this._dataList; }

    get(key: number): Tables.AchievementConfig | undefined { return this._dataMap.get(key); }

    resolve(tables:TablesComponent) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}


export namespace Tables {
export class TbSoundsConfig {
    private _dataMap: Map<number, Tables.SoundsConfig>
    private _dataList: Tables.SoundsConfig[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, Tables.SoundsConfig>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: Tables.SoundsConfig
            _v = new Tables.SoundsConfig(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, Tables.SoundsConfig> { return this._dataMap; }
    getDataList(): Tables.SoundsConfig[] { return this._dataList; }

    get(key: number): Tables.SoundsConfig | undefined { return this._dataMap.get(key); }

    resolve(tables:TablesComponent) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}


export namespace Tables {
export class TbItemConfig {
    private _dataMap: Map<number, Tables.ItemConfig>
    private _dataList: Tables.ItemConfig[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, Tables.ItemConfig>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: Tables.ItemConfig
            _v = new Tables.ItemConfig(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, Tables.ItemConfig> { return this._dataMap; }
    getDataList(): Tables.ItemConfig[] { return this._dataList; }

    get(key: number): Tables.ItemConfig | undefined { return this._dataMap.get(key); }

    resolve(tables:TablesComponent) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}


export namespace Local {
export class TbLocalization {
    private _dataMap: Map<string, Local.Localization>
    private _dataList: Local.Localization[]
    constructor(_json_: any) {
        this._dataMap = new Map<string, Local.Localization>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: Local.Localization
            _v = new Local.Localization(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.key, _v)
        }
    }

    getDataMap(): Map<string, Local.Localization> { return this._dataMap; }
    getDataList(): Local.Localization[] { return this._dataList; }

    get(key: string): Local.Localization | undefined { return this._dataMap.get(key); }

    resolve(tables:TablesComponent) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}



type JsonLoader = (file: string) => any

export class TablesComponent {
    private _TbAchievementConfig: Tables.TbAchievementConfig
    get TbAchievementConfig(): Tables.TbAchievementConfig  { return this._TbAchievementConfig;}
    private _TbSoundsConfig: Tables.TbSoundsConfig
    get TbSoundsConfig(): Tables.TbSoundsConfig  { return this._TbSoundsConfig;}
    private _TbItemConfig: Tables.TbItemConfig
    get TbItemConfig(): Tables.TbItemConfig  { return this._TbItemConfig;}
    private _TbLocalization: Local.TbLocalization
    get TbLocalization(): Local.TbLocalization  { return this._TbLocalization;}

    constructor(loader: JsonLoader) {
        this._TbAchievementConfig = new Tables.TbAchievementConfig(loader('tables_tbachievementconfig'))
        this._TbSoundsConfig = new Tables.TbSoundsConfig(loader('tables_tbsoundsconfig'))
        this._TbItemConfig = new Tables.TbItemConfig(loader('tables_tbitemconfig'))
        this._TbLocalization = new Local.TbLocalization(loader('local_tblocalization'))

        this._TbAchievementConfig.resolve(this)
        this._TbSoundsConfig.resolve(this)
        this._TbItemConfig.resolve(this)
        this._TbLocalization.resolve(this)
    }
}

